stages:
  data_ingestion:
    cmd: python src/MalariaClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/MalariaClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset


  training:
    cmd: python src/MalariaClassifier/pipeline/stage_02_training.py
    deps:
      - src/MalariaClassifier/pipeline/stage_02_training.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion/dataset
    outs:
      - artifacts/training/xception_model.h5
    
  evalution:
    cmd: python src/MalariaClassifier/pipeline/stage_03_evalution.py
    deps:
      - src/MalariaClassifier/pipeline/stage_03_evalution.py
      - artifacts/data_ingestion/dataset
      - params.yaml
      - config/config.yaml
      - artifacts/training/xception_model.h5
    metrics:
      - scores.json:
          cache: False