# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - malaria

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://malaria.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_226256b7b87b4eedae132d9449e2532c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_20f7b61d7fb94ded9b74fb45e7fcbe32 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: malaria.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_226256b7b87b4eedae132d9449e2532c }}/malaria:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'malaria'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c0a54234a6c841449220d7485732945d }}
        images: 'malaria.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_226256b7b87b4eedae132d9449e2532c }}/malaria:${{ github.sha }}'